apiVersion: v1
kind: Service
metadata:
  name: app-b
spec:
  ports:
  - port: 80
  selector:
    app: app-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: httpd:2.4
        ports:
        - containerPort: 80
