apiVersion: v1
kind: Service
metadata:
  name: app-a
spec:
  ports:
  - port: 80
  selector:
    app: app-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: nginx:1.19
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args:
        - "-c"
        - "sleep 120 && nginx -g 'daemon off;'"
